### ISSUE TITLE
Encrypt rootfs.key with EK

### ISSUE THREAD

**Issue by osresearch** [osresearch/safeboot#117]
The EK is decrypt only and the attestation server has the EK's public key. Could it store the root fs key encrypted with the (peristent) EK and send it encrypted with the (ephemeral) key so that there is no sensitive information stored on the attestation server?

**Comment by nicowilliams** [comment]
I know you know the answer by now, but for others watching this, the answer is "no".

While one can use `credentialBlob = TPM2_MakeCredential(EKpub, EKname, small_secret)`, one cannot successfully call `TPM2_ActivateCredential(EK, EK, credentialBlob)` because the `activateHandle` argument of `TPM2_ActivateCredential()` requires `ADMIN` role, and the EK's auth policy does not include the ability to use it to call `TPM2_ActivateCredential(..., EK, ...)`.

The option @osresearch has chosen is to send the client a `TPM2_Duplicate(EKpub, TK)` where `TK` is a transport key generated for the client by the server, and then the client can `TPM2_RSA_Decrypt(TPM2_Load(TPM2_Import(EK, duplicate)), ciphertext)`.  The server stores the `duplicateBlob` output by `TPM2_Duplicate()` and any ciphertexts resulting from calling `Encrypt_TKpub(secret)`.

Another option is to use `TPM2_CreatePrimary()` or `TPM2_CreateLoaded()` to deterministically create a decryption transport key (`TK`) w/o `stClear`.  The client can then enroll the public key of that key along with its `EKpub`/`EKcert`, and the server can store `TKpub` and any secrets encrypted to it.

Another option is to use `TPM2_CreatePrimary()` or `TPM2_CreateLoaded()` to deterministically create a key object of any type w/o `stClear`.  The client can then enroll the name of that object along with its `EKpub`/`EKcert`, and the server can store that name and outputs of `TPM2_MakeCredential(EK, that_name, secret)`.

**Comment by osresearch** [comment]
this is effectively being done now with the transport key https://github.com/osresearch/safeboot/commit/44aa3ab541870047fc350e64904277482823a97c
