### ISSUE TITLE
`die` is annoying

### ISSUE THREAD

**Issue by nicowilliams** [osresearch/safeboot#123]
I've been running @geoffthorpe's mariner workflow for dev work, and I source slightly modified versions of `sbin/tpm2-attest` and `functions.sh` and `workflow/simple-attest-client/run_client.sh` that do not `exit`, with a `die` function that doesn't exit.  Convenient for me.  But `die` really is expected to exit functions because it exits the shell, so having it `return` is not really ok -- for now it works.

Not sure what I'd recommend be done instead.

Also `set -e` is very busted in all the shells, because it doesn't apply to any non-conditional commands executed by functions invoked from conditional commands.  This is absolutely infuriating, and makes shell scripting fraught.  What I normally do about this is either never call shell functions from conditional commands, or always explicitly check every command's status at least in function bodies.

Maybe `xyz || die "message"` should be `xyz || { err "message"; return 1; }` where `err` generally exits, but can be set to not exit.

**Comment by osresearch** [comment]
Having functions `warn` and return failure instead of calling `die` seems like the right choice so that they can be more flexibly used.  This is like the library function that calls `abort()` or `exit()`: it's rude to the caller who might have other cleanup they need to do.

We'll need to make sure that we check the callers of these functions to ensure that the errors are propagated, but that should be doable.

**Comment by nicowilliams** [comment]
Excellent.  I've already started in a local clone.

**Comment by nicowilliams** [comment]
FYI, I'm using this style, based on yours:

```bash
some_func() {
        do_something \
        || die "something failed!" \
        || return 1
        another_thing \
        || die "some other thing failed!" \
        || return 1
}```

with unexpanded tabs.
