### ISSUE TITLE
`openssl rand` or `dd if=/dev/urandom`?

### ISSUE THREAD

**Issue by nicowilliams** [osresearch/safeboot#126]
Or even `tpm2 getrandom`.  Do we have `/dev/urandom` at initramfs time?  But we do have a TPM then, so...

**Comment by osresearch** [comment]
We do have urandom, although there are caveats with it of course and the `dd if=/dev/urandom` has failed in the past due to a short read.  Since we already have `openssl` in the initramfs, I've been using it to get random values with the assumption that it is at least doing the right thing most of the time.

**Comment by nicowilliams** [comment]
Addressed with 7f643d6.
