### ISSUE TITLE
Document safeboot.conf in install process

### ISSUE THREAD

**Issue by Nicocha30** [osresearch/safeboot#34]
Hi!

I ran into some issues when following the install documentation (https://safeboot.dev/install/)
Indeed, the `*-sign` commands use a default `ROOTDEV` parameter (defined in safeboot.conf) to specify the root device during boot.
Maybe it should be documented in the install process that the `local.conf` should be updated? Or could the `*-sign` commands discover the current `ROOTDEV` ? (Using cmdline maybe?)

Thanks,

Nicolas

**Comment by osresearch** [comment]
Setting it in `/etc/safeboot/local.conf` is a good suggestion.  Perhaps on the first `recovery-sign` or `linux-sign` the safeboot script should detect that no `$ROOTDEV` is set and try to determine the currently mounted `/`:
```
mount | awk '/ on \/ / { print $1 }'
```

I think that getting it from `/proc/cmdline` might be problematic if the file system is identified by UUID rather than by volume group.

**Comment by osresearch** [comment]
Added auto discovery of the real root device during signing operations and add `$ROOTDEV` to the `local.conf`. Also add `$HASHDEV` to `local.conf` during `sip-init`.

I need to go through the setup workflow again the be sure that the hash device discovery works with this process.

**Comment by osresearch** [comment]
While researching something else I realized that the UUID to block device can be determined with `blkid`:
```
$ blkid --uuid b270ff8f-4b46-444b-a96e-405f53f20660
/dev/mapper/ubuntu--vg-root
```
