### ISSUE TITLE
Upgrade 0.6 to 0.7 fails at update-initramfs hooks script

### ISSUE THREAD

**Issue by blinkiz** [osresearch/safeboot#68]
I upgraded today from safeboot 0.6 to 0.7.
```
wget https://github.com/osresearch/safeboot/releases/download/release-0.7/safeboot_0.7_amd64.deb
sudo apt install safeboot_0.7_amd64.deb
sudo update-initramfs -u -v
...
Calling hook safeboot-hooks
Adding safeboot /etc/safeboot/safeboot.conf
E: /etc/initramfs-tools/hooks/safeboot-hooks failed with return 2.
Removing /boot/initrd.img-5.4.0-42-generic.dpkg-bak
update-initramfs: failed for /boot/initrd.img-5.4.0-42-generic with 2.
```

So if I look in `/etc/initramfs-tools/hooks/safeboot-hooks` I can see `copy_file safeboot` on line 35 that is successful so the failure is on line 36. 
```
copy_file safeboot-keys "$(dirname "$CERT")/$(basename "$CERT" .pem).pub" "$DIR/cert.pub"
```
So what is `cert.pub`? I do not have this file (yet). Where is `$CERT` defined?

**Comment by osresearch** [comment]
The `safeboot yubikey-init` or `safeboot key-init` now creates three versions of the public keys: the `sbsign` tool wants PEM, the `kmodsign` tool wants DER, the `tpm2-tools` wants a raw public key. The best part about standards...

Since you've upgraded, you don't have the raw public key version in `/etc/safeboot/cert.pub`.  If you used a yubikey, you can generate it with `safeboot yubikey-pubkey`.  If you have a normal openssl key, you can run:

```
openssl x509 \
                -in "/etc/safeboot/signing.key" \
                -noout \
                -pubkey \
                -out "/etc/safeboot/cert.pub"
```

Also, since you've upgraded you might have two initramfs hooks.  The `/etc/initramfs-tools/hooks/tpm-unseal` was renamed to `safeboot-hooks`.  It shouldn't cause any problems to run both, but you can delete the old one.

**Comment by blinkiz** [comment]
Thank you for the answer. Your instruction worked and I now have safeboot 0.7 successfully installed.
I needed to do this for a successful 0.6 to 0.7 upgrade:
```
sudo safeboot yubikey-pubkey /etc/safeboot/cert.pem
sudo rm /etc/initramfs-tools/hooks/tpm-unseal
```
Now `sudo update-initramfs -u` works.
